Some kernels might not have the enable_lmk parameter
droidian/droidian-quirks pull request #2
Opened 2022-06-27 13:19 UTC by nitanmarcel

Some devices might not have the module param `enable_lmk`, for those the lmk needs to be tweaked from the `minfree`, disabled from the kernel or it can also be [easily patched](https://nekobin.com/yeminebuce)?

Also there's a check for adaptive lmk which might not exist at all on some kernel. 

Reference https://gitlab.com/ubports/porting/community-ports/android10/xiaomi-redmi-9c/kernel-xiaomi-mt6765/-/blob/halium10-new/drivers/staging/android/lowmemorykiller.c

2022-06-27 18:34 UTC, g7 requested changes
Thanks! I left a couple of comments

This script was meant as a sort of catch-all for lowmemorykiller needs, exit status is always 0 so that if something is missing is not worrying, but I'm ok with checking for the path as well (and, since we're doing that for `enable_adaptive_lmk`, I think it should be done for `enable_lmk' as well)

2022-06-27 18:34 UTC, g7 commented on debian/droidian-quirks-device.droidian-lmk-disable.service
> +ConditionPathExists=/sys/module/lowmemorykiller/parameters/enable_lmk
I would drop this, some kernels don't expose `enable_lmk`

2022-06-27 18:34 UTC, g7 commented on device/droidian-lmk-disable.sh
> +[ -f /sys/module/lowmemorykiller/parameters/enable_adaptive_lmk ] && echo 0 > /sys/module/lowmemorykiller/parameters/enable_adaptive_lmk
Use `-e` rather than `-f`

2022-06-27 18:51 UTC, nitanmarcel commented on debian/droidian-quirks-device.droidian-lmk-disable.service
> +ConditionPathExists=/sys/module/lowmemorykiller/parameters/enable_lmk
So based on the copy above, just add the check in the script and not for the systemd configuration. Or you're planning on removing it at all?

2022-06-27 18:59 UTC, g7 commented on debian/droidian-quirks-device.droidian-lmk-disable.service
> +ConditionPathExists=/sys/module/lowmemorykiller/parameters/enable_lmk
Yeah, I'd just drop the condition here so that the script always run, it's fine (and preferable) keeping the check in the script itself

2022-07-02 13:37 UTC, g7 approved these changes
Thanks!

2022-07-02 13:38 UTC, merged